### ISSUE TITLE
Unable to generate TypeScript types from SQL queries with sqlx-ts: files not being created

### ISSUE THREAD

**Issue by Leo5878** [JasonShin/sqlx-ts#81] opened 2023-10-25 22:40 UTC
When attempting to run the command: `yarn run sqlx-ts --generate-types --config sqlxrc.json $(pwd)`, it produces the following output. However, the files are not being generated as indicated in the 
```
[INFO] Scanning "path" for SQLs with extension Ts
[INFO] No SQL errors detected!
Done in 0.67s.
```

**Comment by JasonShin** [comment] 2023-10-26 00:51
Hello, two questions
- Please try `yarn run sqlx-ts $(pwd) --generate-types --config sqlxrc.json`
- Could you roughly tell me the structure of your folders and file names? Currently there is a known bug with filenames, will be fixing that soon

**Comment by Leo5878** [comment] 2023-10-26 06:03
@JasonShin
Hello! The command you sent me also didn't work.
I tried it with both the full absolute and relative (./) paths.
Here is my full path: `/home/yoh/web/nodejs/itdo/itdo-bot-fastify`.
Alright, thank you. I'll wait

**Comment by JasonShin** [comment] 2023-10-27 10:36
hello, what are the filenames that sqlx-ts try to pick up?
is it something like `somefile.ts` or `somefile.services.ts`?

**Comment by Leo5878** [comment] 2023-10-27 11:42
Hello, i didn't understand the question. All the output i have is what i sent above. (You're welcome)

**Comment by JasonShin** [comment] 2023-10-27 11:48
Sorry I mean, what are the TypeScript filenames that live under `/home/yoh/web/nodejs/itdo/itdo-bot-fastify`?
(I'd appreciate if you can provide roughly how they look)

For example
```
// /home/yoh/web/nodejs/itdo/itdo-bot-fastify

src
-> main.ts
-> app
-> -> route.service.ts
-> -> business.ts
```

**Comment by Leo5878** [comment] 2023-10-27 12:18
```
├── out
├── package.json
├── sqlxrc.json
├── src
│   ├── controller
│   ├── main.mts
│   ├── model
│   │   ├── main.ts
│   │   ├── tasks.ts
│   │   └── users.ts
│   ├── router
│   │   └── api
│   │       └── v1
│   │           └── main.mts
│   └── types
│       └── main.ts
├── tsconfig.json
├── yarn-error.log
└── yarn.lock
```

**Comment by JasonShin** [comment] 2023-10-27 12:22
@Leo5878 thank you, and which TS files have SQLs?

**Comment by Leo5878** [comment] 2023-10-27 13:20
@JasonShin It seems like I didn't quite understand how the tool works, and I hadn't had any SQL code in my files before this. From the example in the readme, I inserted this code to check:

```javascript
import { sql } from 'sqlx-ts'

const query = sql`SELECT * FROM users;`
```

But it still doesn't generate anything. This is in the "users.ts" file.
Thank

**Comment by JasonShin** [comment] 2023-10-27 14:07
I'm releasing 0.7.0 with a potential fix, I will update you once it's ready
https://github.com/JasonShin/sqlx-ts/pull/80

**Comment by Leo5878** [comment] 2023-10-27 14:50
I tried three options, two of which I described here. The last one was like this:
```bash
yarn run sqlx-ts ./src/model/users.ts --generate-types --config sqlxrc.json
```

Here's the content of my `sqlxrc.json` file:
```
{
  "connections": {
    "default": {
      "DB_TYPE": "postgres",
      "DB_USER": "user",
      "DB_PASS": "pass",
      "DB_HOST": "localhost",
      "DB_NAME": "postgres",
      "DB_PORT": 5432
    }
  }
}
```
The [example](https://jasonshin.github.io/sqlx-ts/reference-guide/2.1.configs-file-based.html) doesn't mention anything about "connections." If you run it without specifying a connection, the CLI will start to give an error, saying that it's missing.

**Comment by JasonShin** [comment] 2023-11-05 00:01
Hello, the reported problem should've been fixed now. It was caused by a bug where sqlx-ts didn't respect `-g` or `--generate-types` when there is a config-file provided. Please try 0.8.0

**Closed by JasonShin** 2023-11-05 00:01 UTC
Labels: bug
