### ISSUE TITLE
Selecting * does not create proper types

### ISSUE THREAD

**Issue by simplenotezy** [JasonShin/sqlx-ts#133] opened 2024-06-26 20:27 UTC
When using this code:

```ts
  const usersQuery = await dataSource.query({
    text: sql`
  SELECT
    *
  FROM
    "user"
  WHERE
    id = ANY($1)
`,
    values: [ids],
  });
```

The following types are generated:

```ts


export type UsersQueryParams = [boolean];


export interface IUsersQueryResult {
    
};


export interface IUsersQueryQuery {
    params: UsersQueryParams;
    result: IUsersQueryResult;
};
```

If I explicitly select a specific field, it works. This is my configuration:

```json
{
  "generate_types": {
    "enabled": true,
    "convertToCamelCaseColumnName": true
  },
  "connections": {
    "default": {
      "DB_TYPE": "postgres",
      "DB_HOST": "localhost",
      "DB_PORT": 26257,
      "DB_USER": "root",
      "DB_PASS": "passwd",
      "DB_NAME": "defaultdb"
    }
  }
}
```

Using the latest and greatest 0.14.0.

My database is CockroachDB. Not sure if it has anything to do with it, but it is postgres based.

**Comment by JasonShin** [comment] 2024-06-27 12:56
This is probably the same bug as the other issue https://github.com/JasonShin/sqlx-ts/issues/134 - this is caused by quoted table name. I can see the wildcard queries are working correctly without the quotes around the table name

```
SELECT
    *
  FROM
    user
  WHERE
    id = ANY($1)
```

The fix for this is being tracked here https://github.com/JasonShin/sqlx-ts/pull/135

**Closed** 2024-09-23 22:52 UTC
